Add pdf report download function - PE-159
proversity-org/xblock-activetable pull request #2
Opened 2018-10-26 16:46 UTC by Squirrel18

## Description:

This PR is submitted according to [JIRA ticket PE-159](https://proversity.atlassian.net/browse/PE-159).

Adds the function to download a PDF report of actual table values.

## Test:

Inside of a unit with xblock Activetable problem, push the button "Download" and verified that the pdf report is correct downloaded.

## Reviewers:

- [ ] @diegomillan 
- [ ] @ericfab179

2018-10-26 19:23 UTC, diegomillan requested changes

2018-10-26 19:23 UTC, diegomillan commented on activetable/activetable.py
> +        except Exception as exp:
Is it possible to use another Exception class, maybe a list of known Exceptions for the `try` part.

2018-10-29 17:44 UTC, Squirrel18 commented on activetable/activetable.py
> +        except Exception as exp:
I've been looking for a known exception that could be raised by the reportlab classes and methods, but the documentation is not clear in that case, and that's why all exceptions will be catched. @diegomillan

2018-10-30 20:05 UTC, diegomillan approved these changes

2018-10-30 23:18 UTC, merged